ALTER TABLE public.avaliadores_sessao
  ADD COLUMN IF NOT EXISTS cpf text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS nivel text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS semestre text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS periodo text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS codigo_turma text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT '';